Imports System.Data
Imports System.Web.Services
Imports System.IO
Imports System.Web.Configuration
Imports System.Web.Script.Serialization
Imports Newtonsoft.Json.Linq

Partial Class Approval
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        ' DAL_API.Billing("0027401685", "100", "0059739507", "100", "MBS credit", "12342345678")


        If Session("USERID") Is Nothing Then Response.Redirect("login.aspx")
        If Not IsPostBack Then
            If Session("Role") = "Reviewer" Then Response.Redirect("Preview.aspx")
            If Session("Role") = "Approver" Then
                lblUser.Text = Session("BranchName")
                SelectActivities("All")
            Else
                Response.Redirect("login.aspx")
            End If
        End If
    End Sub
    Private Sub SelectActivities(ByVal type_ As String)
        ' If HttpContext.Current.Session("BranchName") Is Nothing Then HttpContext.Current.Response.Redirect("Login.aspx")
        Dim dt As DataTable = Nothing
        If type_ = "All" Then
            dt = BLL._selectApproval(Session("Branch"))
            If dt.Rows.Count > 0 Then
                If dt.Rows(0).Item(7) < 3 Then lblTop.Text = dt.Rows(0).Item(7) Else lblTop.Text = "3"
            End If
        ElseIf type_ = "Filter" Then
            dt = BLL._selectApprovalbyFilter(Session("Branch"), txtAccountNo.Text)
            If dt.Rows.Count > 0 Then
                lblTop.Text = dt.Rows(0).Item(7)
            End If
        ElseIf type_ = "Filter-All" Then
            dt = BLL._selectApprovalbyFilter(Session("Branch"), "Filter-All")
            If dt.Rows.Count > 0 Then
                lblTop.Text = dt.Rows(0).Item(7)
            End If

        End If

        tbActivityBody.InnerHtml = ""
        If dt.Rows.Count = 0 Then
            tbActivityFoot.Visible = False
            tbActivityHead.Visible = False
            tbActivityBody.InnerHtml = "<tr><td colspan=""8"">No statements have been generated by " & lblUser.Text & ".</td></tr>"
        Else
            For i As Integer = 0 To dt.Rows.Count - 1
                tbActivityBody.InnerHtml += "<tr><td>" & dt.Rows(i).Item(1) & "</td><td>" & dt.Rows(i).Item(2) & "</td><td>" & dt.Rows(i).Item(3) &
                    "</td><td>" & dt.Rows(i).Item(4) & "</td><td># " & dt.Rows(i).Item(0) & "</td><td>" & dt.Rows(i).Item(5).ToString() &
                    "</td><td><a style=""cursor:pointer"" onclick=""jPending('" & dt.Rows(i).Item(0) & "')"" >"
                'If dt.Rows(i).Item(8) = "Print" Then tbActivityBody.InnerHtml += "')"" href='statement/" & dt.Rows(i).Item(0) & ".pdf'>" Else tbActivityBody.InnerHtml += "')"" href=""javascript:void"" >"
                'If dt.Rows(i).Item(8) = "Print" Then tbActivityBody.InnerHtml += "')"" href='statement/" & dt.Rows(i).Item(0) & ".pdf' target=""_blank"">" Else tbActivityBody.InnerHtml += "')"" href=""javascript:void"" >"
                tbActivityBody.InnerHtml += dt.Rows(i).Item(8) & "</a></td></tr>"
            Next
            'If CDbl(dt.Rows(0).Item(7)) > 3 Then lblTop.Text = "3" Else lblTop.Text = dt.Rows(0).Item(7)
            lblTotal.Text = dt.Rows(0).Item(7)
        End If
    End Sub

    <WebMethod()>
    Public Shared Function _MakePayment(ByVal ticket As String) As String
        'customerBal can be gotten from account enquiry. else, it will be detected during billing
        'Dim customerBal As Double = 50000000.0
        'Dim sendStatus As String = ""
        ' Dim solID As String = BLL._selectSolIDFromBranchID(HttpContext.Current.Session("USERID"))
        Dim wqAmount As Decimal
        Dim DiamondAMount As Decimal
        HttpContext.Current.Session("REQUESTID") = ticket
        Dim newTicket As String = BLL._SelectTicketStatusFromTicketID(ticket)
        Try
            Dim result As String = ""
            'result += "%" & "Authorization/" & ticket & ".pdf"

            Dim dt7 As DataTable = BLL._ApprovalInfo(ticket)
            'If customerBal >= CDbl(dt7.Rows(0).Item(16).ToString) Then
            '    sendStatus = "1"
            'Else
            '    sendStatus = "0"
            'End If
            Dim validPrice As String = BLL._selectvalidprice()

            If validPrice.Split("|")(1).ToString = "0" Then
                wqAmount = (CDbl(dt7.Rows(0).Item("page")) * CDec(validPrice.Split("|")(4)) + (0.7 * CDec(dt7.Rows(0).Item("additional")))) '* 1.05
            Else
                wqAmount = (CDec(validPrice.Split("|")(4)) + 0.7 * (CDec(dt7.Rows(0).Item("total")))) '* 1.05
            End If
            DiamondAMount = (((CDec(validPrice.Split("|")(0)) - CDec(validPrice.Split("|")(4))) * CDbl(dt7.Rows(0).Item("page")) + 0.3 * (CDec(dt7.Rows(0).Item("additional"))))) '+ (wqAmount * 0.05)
            Dim vatAmount As Decimal = CDec(dt7.Rows(0).Item("total")) - (wqAmount + DiamondAMount)


            If dt7.Rows(0).Item(0).ToString = "00298465031" Then
                If newTicket = "1" Then
                    result = "True%" & "ticket/" & ticket & ".pdf"
                Else
                    result = "True%" & "receipt/" & ticket & ".pdf"
                End If
                BLL._UpdateEmailAndSMSAlert(ticket, "1")
                BLL._updateStatus(ticket, "Test")
                BLL._updateTestCharge(ticket)
                BLL._insertAuditLogs(ticket, dt7.Rows(0).Item(3), HttpContext.Current.Session("Role"), ticket, "Sent", Now)

            Else

                Dim billRes As String = ""
                Dim avl_bal As String = "0"
                Dim serv As New DiamondService.Service()
                Dim resArr() As String = serv.getAccountDetails(dt7.Rows(0).Item(0))
                If resArr(0) = "00" Then



                    Try
                        Dim j As Object = New JavaScriptSerializer().Deserialize(Of Object)(resArr(1))

                        Dim allData As JObject = JObject.Parse(j)

                        If allData("ResponseCode") = "00" Then

                            avl_bal = allData("Details")("AvailableBalance").ToString()

                        End If
                        If avl_bal = "0" Then
                            billRes = ""
                        ElseIf CDbl(dt7.Rows(0).Item(16)) > CDbl(avl_bal) Then
                            billRes = "Insufficient Funds"
                        Else
                            billRes = ""
                        End If
                    Catch ex As Exception
                        billRes = ""
                    End Try
                End If
                If billRes = "" Then
                    If wqAmount = 0 Then
                        billRes = DAL_API.Billing(dt7.Rows(0).Item(0), CDbl(dt7.Rows(0).Item(16)),
                                                            WebConfigurationManager.AppSettings("DiamondAcctNo").ToString(), DiamondAMount,
                                                   WebConfigurationManager.AppSettings("VATAcctNo").ToString(), vatAmount,
                                                            ticket.ToString, dt7.Rows(0).Item(0) & "/mybankStatement STMNT CHRG")

                    Else
                        billRes = DAL_API.Billing(dt7.Rows(0).Item(0), CDbl(dt7.Rows(0).Item(16)),
                                                            WebConfigurationManager.AppSettings("wqAcctNo").ToString(), wqAmount,
                                                            WebConfigurationManager.AppSettings("DiamondAcctNo").ToString(), DiamondAMount,
                                                            WebConfigurationManager.AppSettings("VATAcctNo").ToString(), vatAmount, ticket.ToString, dt7.Rows(0).Item(0) & "/mybankStatement STMNT CHRG")

                    End If
                Else
                    billRes = billRes
                End If


                If billRes.ToLower = "00" Then

                    Dim sentResult As String = sendRequestToService(ticket)
                    If sentResult.Split("%")(0) = "True" Then
                        If newTicket = "1" Then
                            result = "True%" & "ticket/" & ticket & ".pdf"
                        Else
                            result = "True%" & "receipt/" & ticket & ".pdf"
                        End If

                        BLL._updateStatus(ticket, "SENT")
                        BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), dt7.Rows(0).Item(3), HttpContext.Current.Session("Role"), ticket, "Sent", Now)
                        BLL._UpdateEmailAndSMSAlert(ticket.ToString, "1")
                    Else
                        BLL._updateStatus(ticket, "NOT SENT")
                        BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), dt7.Rows(0).Item(3), HttpContext.Current.Session("Role"), ticket, "Not Sent", Now)
                        'BLL._UpdateEmailAndSMSAlert(ticketNo.ToString, "1")
                    End If
                ElseIf billRes.ToLower = "insufficient funds" Then
                    '  BLL._updateStatus(ticket, "Make Payment")
                    BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), dt7.Rows(0).Item(3), HttpContext.Current.Session("Role"), HttpContext.Current.Session("REQUESTID"), "Transaction Failed due to insufficient fund", Now)
                    Return "False%" & "Insufficient Fund"

                Else
                    '   BLL._updateStatus(ticket, "Make Payment")
                    BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), dt7.Rows(0).Item(3), HttpContext.Current.Session("Role"), HttpContext.Current.Session("REQUESTID"), "Transaction Failed (Service)", Now)
                        Return "False%" & "Transaction Failed. Error code:" + billRes
                    End If
                End If
                Return result
        Catch ex As Exception
            Return "False%" & ex.Message
        End Try
    End Function
    <WebMethod()>
    Public Shared Function sendStatement(ByVal value As String) As String
        Dim ticketNo As String = value.Split("_")(3)
        Dim result As String = Nothing
        Dim dtDetails As DataRow = BLL._selectActivitybyRequestID(ticketNo).Rows(0)
        Dim wqAmount As Decimal = 0.0
        Dim custAmount As Decimal = CDec(dtDetails.Item(21))
        ' Dim solID As String = BLL._selectSolIDFromBranchID(HttpContext.Current.Session("USERID"))
        Dim DiamondAmount As Decimal = custAmount
        If HttpContext.Current.Session("USERID") Is Nothing Then HttpContext.Current.Response.Redirect("Login.aspx")

        Dim newTicket As String = BLL._SelectTicketStatusFromTicketID(ticketNo)
        Dim validPrice As String = BLL._selectvalidprice()
        If validPrice.Split("|")(1).ToString = "0" Then
            wqAmount = (CDec(dtDetails.Item(18)) * CDec(validPrice.Split("|")(4)) + (0.7 * CDec(dtDetails.Item(20)))) '* 1.05
        Else
            wqAmount = (CDec(validPrice.Split("|")(4)) + 0.7 * (CDec(dtDetails.Item(20)))) '* 1.05
        End If
        DiamondAmount = ((((CDec(validPrice.Split("|")(0)) - CDec(validPrice.Split("|")(4))) * CDec(dtDetails.Item(18)) + 0.3 * (CDec(dtDetails.Item(20))))))
        Dim vatAmount As Decimal = CDec(dtDetails.Item(21)) - (wqAmount + DiamondAmount)

        'The next line is the right for live and the next should be removed
        If dtDetails.Item(3).ToString = "0059739507" Then
            ' If 1 = 1 Then
            Dim sentResult As String = sendRequestToService(ticketNo)
            If sentResult.Split("%")(0) = "True" Then
                If newTicket = "1" Then
                    result = "True%" & "ticket/" & ticketNo & ".pdf"
                Else
                    result = "True%" & "receipt/" & ticketNo & ".pdf"
                End If
                BLL._UpdateEmailAndSMSAlert(ticketNo.ToString, "1")
                'FOR LIVE, uncomment the commented and remove the next uncommented
                'BLL._updateStatus(ticketNo, "Test")
                BLL._updateTestCharge(ticketNo)
                ' BLL._updateStatus(ticketNo, "SENT")
                BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), value.Split("_")(1), HttpContext.Current.Session("Role"), ticketNo, "Sent", Now)

            End If

        Else
            Dim billRes As String = ""
            Dim avl_bal As String = "0"
            If dtDetails.Item(24).ToString = "1" Then
                billRes = "00"
            Else

                Dim serv As New DiamondService.Service()
                Dim resArr() As String = serv.getAccountDetails(dtDetails.Item(3))
                If resArr(0) = "00" Then



                    Try
                        Dim j As Object = New JavaScriptSerializer().Deserialize(Of Object)(resArr(1))

                        Dim allData As JObject = JObject.Parse(j)

                        If allData("ResponseCode") = "00" Then

                            avl_bal = allData("Details")("AvailableBalance").ToString()

                        End If
                        If avl_bal = "0" Then
                            billRes = ""
                        ElseIf CDbl(custAmount) > CDbl(avl_bal) Then
                            billRes = "Insufficient Funds"
                        Else
                            billRes = ""
                        End If
                    Catch ex As Exception
                        billRes = ""
                    End Try
                End If
            End If

            If billRes = "" Then
                If wqAmount = 0 Then
                    billRes = DAL_API.Billing(dtDetails.Item(3), custAmount,
                                                        WebConfigurationManager.AppSettings("DiamondAcctNo").ToString(), DiamondAmount,
                                               WebConfigurationManager.AppSettings("VATAcctNo").ToString(), vatAmount,
                                                         dtDetails.Item(3) & "/mybankStatement STMNT CHRG", ticketNo.ToString)

                Else
                    billRes = DAL_API.Billing(dtDetails.Item(3), custAmount,
                                                        WebConfigurationManager.AppSettings("wqAcctNo").ToString(), wqAmount,
                                                        WebConfigurationManager.AppSettings("DiamondAcctNo").ToString(), DiamondAmount,
                                                        WebConfigurationManager.AppSettings("VATAcctNo").ToString(), vatAmount, ticketNo.ToString,
                                              dtDetails.Item(3) & "/mybankStatement STMNT CHRG")

                End If
            Else
                billRes = billRes
            End If


            If billRes.ToLower = "00" Then
                Dim sentResult As String = sendRequestToService(ticketNo)
                If sentResult.Split("%")(0) = "True" Then
                    If newTicket = "1" Then
                        result = "True%" & "ticket/" & ticketNo & ".pdf"
                    Else
                        result = "True%" & "receipt/" & ticketNo & ".pdf"
                    End If

                    BLL._updateStatus(ticketNo, "SENT")
                    BLL._insertAuditLogsBranch(HttpContext.Current.Session("USERID"), value.Split("_")(1), HttpContext.Current.Session("Role"), ticketNo, "Sent", Now, HttpContext.Current.Session("Branch"))
                    BLL._UpdateEmailAndSMSAlert(ticketNo.ToString, "1")
                Else
                    BLL._updateStatus(ticketNo, "NOT SENT")
                    BLL._insertAuditLogsBranch(HttpContext.Current.Session("USERID"), value.Split("_")(1), HttpContext.Current.Session("Role"), ticketNo, "Not Sent", Now, HttpContext.Current.Session("Branch"))
                    'BLL._UpdateEmailAndSMSAlert(ticketNo.ToString, "1")
                End If

            ElseIf billRes.ToLower = "insufficient funds" Then
                ' BLL._updateStatus(ticketNo, "Make Payment")
                BLL._insertAuditLogsBranch(HttpContext.Current.Session("USERID"), value.Split("_")(1), HttpContext.Current.Session("Role"), ticketNo, "Transaction Failed. Insufficient fund (Diamond Billing Service)", Now, HttpContext.Current.Session("Branch"))
                Return "False%" & "Insufficient Fund"
            Else
                '  BLL._updateStatus(ticketNo, "Make Payment")
                BLL._insertAuditLogsBranch(HttpContext.Current.Session("USERID"), value.Split("_")(1), HttpContext.Current.Session("Role"), ticketNo, "Transaction Failed (Diamond Billing Service)", Now, HttpContext.Current.Session("Branch"))
                result = "False%" & "Transaction Failed due to " + billRes
            End If
        End If

        Return result


    End Function
    Shared Function sendRequestToService(ByVal ticketNo As String) As String
        Try
            Dim oFileInfo As FileInfo = New FileInfo("D:\mybankStatementRepository\statement\" & ticketNo & ".pdf")
            'put condition for sending CSV
            Dim sendToService As New SendToService(oFileInfo, ticketNo.ToString)
            Dim outcome As String = sendToService.SendPDF()
            '     Dim outcome As String = BLL.doFileUploadViaWebService(oFileInfo, ticketNo)            
            If outcome.ToLower = "file sent successfully" Or outcome.ToLower = "file delivered successfully" Then
                Dim statusCSV As String
                statusCSV = BLL._selectCSVStatus(ticketNo)

                If statusCSV = "1" Then
                    Dim csvFileInfo As FileInfo = New FileInfo(("D:\mybankStatementRepository\statementCSV\" & ticketNo & ".zip"))
                    Dim sendCsvToService As New SendCSVtoService(csvFileInfo, ticketNo)
                    sendCsvToService.doCSVFileUploadViaWebService()
                End If
                If BLL._GetFormat("1", ticketNo) = "1" Then
                    Dim jsonFileInfo As FileInfo = New FileInfo(("D:\mybankStatementRepository\statementJSON\" & ticketNo & ".zip"))
                    Dim sendJsonToService As New SendJsonToService(jsonFileInfo, ticketNo)
                    sendJsonToService.doJSONFileUploadViaWebService()
                End If
                Return "True%" & outcome
            Else
                Return "False%" & outcome
            End If

        Catch ex As Exception
            Return "False%" & ex.Message()
        End Try
    End Function
    <WebMethod()> _
    Public Shared Function _ApprovalInfo(ByVal ticket As String) As String
        Dim customerBal As Double = 500000.0
        Dim sendStatus As String = ""
        Try
            Dim result As String = ""
            'If (File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~\Authorization\" + ticket + "_wm.pdf"))) Then
            '    result += "%" & "Authorization/" & ticket & "_wm.pdf"
            'Else
            result += "%" & "Authorization/" & ticket & ".pdf"
            '   End If

            Dim dt7 As DataTable = BLL._ApprovalInfo(ticket)
            If customerBal >= CDbl(dt7.Rows(0).Item(16).ToString) Then
                sendStatus = "1"
            Else
                sendStatus = "0"
            End If
            Dim debitAccount As String = ""
            If dt7.Rows(0).Item(21).ToString = "" Then
                debitAccount = dt7.Rows(0).Item(0).ToString
            End If
            Dim tdWaive As String = "No"
            If dt7.Rows(0).Item(20).ToString = 1 Then
                tdWaive = "Yes"
            End If
            If result.Split("%")(0) = "0" Then
                Return "False%" & result.Split("%")(1)
            Else
                result = "True%" & result.Split("%")(1) & "%" & dt7.Rows(0).Item(0) & "%" & HttpUtility.HtmlDecode(dt7.Rows(0).Item(1)) & "%" & dt7.Rows(0).Item(2) & "-14" & "%" & dt7.Rows(0).Item(3)

                Dim dt2 As DataTable = BLL._selectApplicant(ticket)
                If dt2.Rows.Count = 0 Then
                    result += "%"
                Else
                    For i As Integer = 0 To dt2.Rows.Count - 1
                        If i = 0 Then result += "%"
                        result += HttpUtility.HtmlDecode(dt2.Rows(i).Item(1)) & "<br />"
                    Next
                End If
                result += "%" & dt7.Rows(0).Item(4) & "%" & dt7.Rows(0).Item(5) & "%" & dt7.Rows(0).Item(6)
                '   Dim dt1 As DataTable

                '   dt1 = DAL_API.Signatories(dt7.Rows(0).Item(0), Utility.getCountryCodeFromCountry(HttpContext.Current.Session("Country")))

                Dim dt1 As DataTable = BLL._selectSignatoriesNew(ticket)
                If dt1 Is Nothing Then
                    result += "%<i>  </i>"
                ElseIf dt1.Rows.Count = 0 Then
                    result += "%<i>No signatory</i>"
                Else
                    For i As Integer = 0 To dt1.Rows.Count - 1
                        If i = 0 Then result += "%"
                        result += HttpUtility.HtmlDecode(dt1.Rows(i).Item(0)) & "<br />"
                    Next
                    result = result.Substring(0, result.Length - 6)
                End If


                result += "%" & dt7.Rows(0).Item(7) & "%" & dt7.Rows(0).Item(8) &
                    "%" & dt7.Rows(0).Item(19) & " " & CDbl(dt7.Rows(0).Item(9)).ToString("#,##0.00") & "%" & dt7.Rows(0).Item(19) & " " & CDbl(dt7.Rows(0).Item(10)).ToString("#,##0.00") & "%" &
                    dt7.Rows(0).Item(19) & " " & CDbl(dt7.Rows(0).Item(11)).ToString("#,##0.00") & "%" _
                    & dt7.Rows(0).Item(19) & " " & CDbl(dt7.Rows(0).Item(12)).ToString("#,##0.00") & "%" _
                    & CDbl(dt7.Rows(0).Item(13)).ToString("#,##0") & "%" _
                    & "NGN  " & CDbl(dt7.Rows(0).Item(14)).ToString("#,##0.00") & "%" & "NGN  " & CDbl(dt7.Rows(0).Item(15)).ToString("#,##0.00") &
                    "%" & "NGN  " & CDbl(dt7.Rows(0).Item(16)).ToString("#,##0.00") & "%" & "NGN  " & CDbl(dt7.Rows(0).Item(17)).ToString("#,##0.00") & "%" & sendStatus & "%" & tdWaive & "%" & debitAccount
                Return result
            End If
        Catch ex As Exception
            Return "False%" & ex.Message
        End Try
    End Function
    <WebMethod()> _
    Public Shared Function declineStatement(ByVal value As String) As String
        Dim ticketNo As String = value.Split("~/")(0).Split("-")(0)
        BLL._insertDeclinedComment(value.Split("~/")(3), ticketNo)
        BLL._updateStatus(ticketNo, "Declined")
        BLL._insertAuditLogs(HttpContext.Current.Session("USERID"), value.Split("~/")(1), HttpContext.Current.Session("Role"), ticketNo, "Declined", Now)
        BLL._SendDeclineAcknowledgement(ticketNo)
        Return "1"

    End Function
    Protected Sub aViewAll_ServerClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles aViewAll.ServerClick
        If aViewAll.InnerText = "View Top 3" Then
            SelectActivities("All")
            aViewAll.InnerText = "View all"
        ElseIf aViewAll.InnerText = "View all" Then
            SelectActivities("Filter-All")
            aViewAll.InnerText = "View Top 3"
        End If
    End Sub
End Class
